# Sena Labs: rekt.news Web Scraping Activity

##### Goal: Extract attack/exploit specific data from html/xml text data
Extract vectors: protocol_name, date, amount_lost

The following data extracted will be an introductory method to how the Sena REKT Report dataset will use methods such as Python webscraping to autonomously upload and valid attack data within the DeFi ecosystem. The following webscrapin method is more efficient than initial manual data entry that will be needed later in validation and data cleaning.

In [1]:
import pandas as pd
from pandas import DataFrame

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import requests
import re
from bs4 import BeautifulSoup

%matplotlib inline

In [2]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [3]:
url = "https://rekt.news/leaderboard"
page = requests.get(url)
html = urlopen(url)

In [4]:
def getHTMLdoc(url):
        response = requests.get(url)
        return response.text

In [5]:
html_doc = getHTMLdoc(url)

In [6]:
soup = BeautifulSoup(html_doc, 'html.parser')

In [7]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <title>
   Rekt -
   <!-- -->
   Leaderboard
  </title>
  <meta content="DeFi / Crypto - Investigative journalism &amp;amp; creative commentary" name="description"/>
  <meta charset="utf-8"/>
  <link href="https://raw.githubusercontent.com/RektHQ/Assets/main/images/favicon.png" rel="icon" type="image/png"/>
  <link href="https://www.rekt.news/" rel="canonical"/>
  <meta content="True" name="HandheldFriendly"/>
  <meta content="320" name="MobileOptimized"/>
  <meta content="initial-scale=1.0, width=device-width" name="viewport"/>
  <meta content="Rekt - Leaderboard" name="og:title"/>
  <meta content="DeFi / Crypto - Investigative journalism &amp;amp; creative commentary" property="og:description"/>
  <meta content="https://raw.githubusercontent.com/RektHQ/Assets/main/images/banner-1200-675.png" property="og:image"/>
  <meta content="https://www.rekt.news/" property="og:url"/>
  <meta content="website" property="og:type"/>
  <meta content="rekt" property="og:site_name"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="Rekt - Leaderboard" name="twitter:title"/>
  <meta content="DeFi / Crypto - Investigative journalism &amp;amp; creative commentary" name="twitter:description"/>
  <meta content="https://raw.githubusercontent.com/RektHQ/Assets/main/images/banner-1200-675.png" name="twitter:image"/>
  <meta content="https://www.rekt.news/" name="twitter:url"/>
  <meta content="@RektHQ" name="twitter:site"/>
  <link href="https://fonts.gstatic.com" rel="preconnect"/>
  <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-5T3NB49M5Z">
  </script>
  <script async="">
   function gtag(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[],gtag("js",new Date),gtag("config","G-5T3NB49M5Z");
  </script>
  <meta content="24" name="next-head-count"/>
  <script>
   (function() {
                  try {
                    var storedTheme = localStorage.getItem('REKT_THEME') || 'light';
                    document.documentElement.setAttribute('data-theme', storedTheme);
                    if (document.body) {
                      document.body.className = storedTheme;
                      document.body.style.colorScheme = storedTheme;
                    }
                  } catch (e) {
                    console.error(e);
                  }
                })();
  </script>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link as="style" crossorigin="" href="/_next/static/css/0e5cf0669a7a5f49.css" rel="preload"/>
  <link crossorigin="" data-n-g="" href="/_next/static/css/0e5cf0669a7a5f49.css" rel="stylesheet"/>
  <noscript data-n-css="">
  </noscript>
  <script crossorigin="" defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/webpack-614496a017abf22a.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/framework-fee8a7e75612eda8.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/main-606f49ebc9265178.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/pages/_app-8ee3ac0ac9179f06.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/fea29d9f-78898eea6c0583fc.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/41155975-32d7ed6514d1dbe3.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/37a763b4-aa123875495257aa.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/6a4d9673-88ba258819ea9c79.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/117b9d7f-3ad57b4cb2e1b65f.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/e21e5bbe-b69d61ae2a4abd5f.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/fc83e031-7f31a6d02bf69edb.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/520c8229-bdca3b68bcd7231a.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/5209-2b822012030e7fd3.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/2279-02e19e09eb5ee490.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/229-5678e3c15fb5f305.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/8035-de0fc20f1722862e.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/3225-1e8cb494a7a893dd.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/1850-c90eb2341b1aedfd.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/7010-54b3e054d1eadf6c.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/chunks/pages/leaderboard-5d8660dadb506e1d.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/EGTGnCI2ZLu5gus_jz67Q/_buildManifest.js">
  </script>
  <script crossorigin="" defer="" src="/_next/static/EGTGnCI2ZLu5gus_jz67Q/_ssgManifest.js">
  </script>
  <style data-href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;display=swap">
   @font-face{font-family:'Roboto Mono';font-style:italic;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xoDF4xlVMF-BfR8bXMIjhOsXG-q2oeuFoqFrlnAOW-&skey=26ea178546e32190&v=v31) format('woff')}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vqPQA&skey=7b92570108d40690&v=v31) format('woff')}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_7PqPQA&skey=7b92570108d40690&v=v31) format('woff')}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:600;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_AP2PQA&skey=7b92570108d40690&v=v31) format('woff')}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xuDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_Of2PQA&skey=7b92570108d40690&v=v31) format('woff')}@font-face{font-family:'Roboto Mono';font-style:italic;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xoDF4xlVMF-BfR8bXMIjhOsXG-q2oeuFoqFrlnANW3Cp-eTIwsa4YaDA&skey=26ea178546e32190&v=v31) format('woff');unicode-range:U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F}@font-face{font-family:'Roboto Mono';font-style:italic;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xoDF4xlVMF-BfR8bXMIjhOsXG-q2oeuFoqFrlnANW-Cp-eTIwsa4YaDA&skey=26ea178546e32190&v=v31) format('woff');unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Roboto Mono';font-style:italic;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xoDF4xlVMF-BfR8bXMIjhOsXG-q2oeuFoqFrlnANW5Cp-eTIwsa4YaDA&skey=26ea178546e32190&v=v31) format('woff');unicode-range:U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF}@font-face{font-family:'Roboto Mono';font-style:italic;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xoDF4xlVMF-BfR8bXMIjhOsXG-q2oeuFoqFrlnANW1Cp-eTIwsa4YaDA&skey=26ea178546e32190&v=v31) format('woff');unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB}@font-face{font-family:'Roboto Mono';font-style:italic;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xoDF4xlVMF-BfR8bXMIjhOsXG-q2oeuFoqFrlnANW0Cp-eTIwsa4YaDA&skey=26ea178546e32190&v=v31) format('woff');unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Roboto Mono';font-style:italic;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/l/font?kit=L0xoDF4xlVMF-BfR8bXMIjhOsXG-q2oeuFoqFrlnANW6Cp-eTIwsa4Y&skey=26ea178546e32190&v=v31) format('woff');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhGq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhPq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhIq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhEq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhFq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhGq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhPq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhIq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhEq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhFq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:500;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:600;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhGq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:600;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhPq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:600;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhIq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:600;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhEq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:600;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhFq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:600;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhGq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhPq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhIq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhEq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhFq3-cXbKDO1w.woff2) format('woff2');unicode-range:U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF}@font-face{font-family:'Roboto Mono';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}
  </style>
 </head>
 <body>
  <div id="__next">
   <div>
    <header class="site-head">
     <div class="site-head-content inner">
      <a href="/">
       <img alt="logo" class="site-logo inv-asset" src="https://raw.githubusercontent.com/rekthq/assets/main/images/logo.svg"/>
      </a>
      <div class="hidden md:block">
       <nav>
        <a class="nav-item" href="/termAndConditions">
         t&amp;c
        </a>
        <span class="divider">
        </span>
        <a class="nav-item" href="https://www.youtube.com/@RektNews./videos" rel="noopener noreferrer" target="_blank">
         videos
        </a>
        <span class="divider">
        </span>
        <a class="nav-item nav-item-active" href="/leaderboard">
         leaderboard
        </a>
        <span class="divider">
        </span>
        <a class="nav-item" href="/research">
         research
        </a>
        <span class="divider">
        </span>
        <button aria-expanded="false" aria-haspopup="menu" class="nav-item font-bold px-3 py-1 transition-colors duration-150 hover:bg-accent hover:text-accent-foreground focus:outline-none focus:bg-accent focus:text-accent-foreground rounded" data-state="closed" id="radix-:Rj4im:" style="background:none;border:none;cursor:pointer" type="button">
         tools
        </button>
        <span class="divider">
        </span>
        <div>
         <div class="flex gap-2">
          <button class="text-xl md:text-[16px]">
           log in
          </button>
         </div>
        </div>
       </nav>
      </div>
      <div class="md:hidden flex gap-2 items-center">
       <div>
        <div class="flex gap-2">
         <button class="text-xl md:text-[16px]">
          log in
         </button>
        </div>
       </div>
       <span class="divider pr-2">
       </span>
       <button aria-expanded="false" aria-haspopup="menu" data-state="closed" id="radix-:R7kim:" type="button">
        <svg class="w-8 h-8" fill="currentColor" height="1em" stroke="currentColor" stroke-width="0" viewbox="0 0 448 512" width="1em" xmlns="http://www.w3.org/2000/svg">
         <path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z">
         </path>
        </svg>
       </button>
      </div>
     </div>
    </header>
    <main class="content" role="main">
     <div class="leaderboard">
      <input class="search-input" placeholder="Search...." type="text" value=""/>
      <div class="leaderboard-content">
       <ol class="leaderboard-column" start="1">
        <li>
         <div class="leaderboard-row">
          <span class="leaderboard-index-l">
           1
           <!-- -->
           .
          </span>
          <div>
           <div class="leaderboard-row-title">
            <a href="/the-one-that-got-away">
             The One That Got Away
             <!-- -->
             <span class="leaderboard-audit">
              N/A
             </span>
            </a>
           </div>
           <div class="leaderboard-row-details">
            $
            <!-- -->
            14,847,374,246
            <!-- -->
            |
            <!-- -->
            12/20/2020
           </div>
          </div>
         </div>
        </li>
        <li>
         <div class="leaderboard-row">
          <span class="leaderboard-index-l">
           2
           <!-- -->
           .
          </span>
          <div>
           <div class="leaderboard-row-title">
            <a href="/bybit-rekt">
             ByBit - Rekt

In [8]:
# Get the title
title = soup.title
print(title)

<title>Rekt - <!-- -->Leaderboard</title>

In [9]:
header = soup.header()
print(header)

[<div class="site-head-content inner"><a href="/"><img alt="logo" class="site-logo inv-asset" src="https://raw.githubusercontent.com/rekthq/assets/main/images/logo.svg"/></a><div class="hidden md:block"><nav><a class="nav-item" href="/termAndConditions">t&amp;c</a><span class="divider"></span><a class="nav-item" href="https://www.youtube.com/@RektNews./videos" rel="noopener noreferrer" target="_blank">videos</a><span class="divider"></span><a class="nav-item nav-item-active" href="/leaderboard">leaderboard</a><span class="divider"></span><a class="nav-item" href="/research">research</a><span class="divider"></span><button aria-expanded="false" aria-haspopup="menu" class="nav-item font-bold px-3 py-1 transition-colors duration-150 hover:bg-accent hover:text-accent-foreground focus:outline-none focus:bg-accent focus:text-accent-foreground rounded" data-state="closed" id="radix-:Rj4im:" style="background:none;border:none;cursor:pointer" type="button">tools</button><span class="divider"></span><div><div class="flex gap-2"><button class="text-xl md:text-[16px]">log in</button></div></div></nav></div><div class="md:hidden flex gap-2 items-center"><div><div class="flex gap-2"><button class="text-xl md:text-[16px]">log in</button></div></div><span class="divider pr-2"></span><button aria-expanded="false" aria-haspopup="menu" data-state="closed" id="radix-:R7kim:" type="button"><svg class="w-8 h-8" fill="currentColor" height="1em" stroke="currentColor" stroke-width="0" viewbox="0 0 448 512" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path></svg></button></div></div>, <a href="/"><img alt="logo" class="site-logo inv-asset" src="https://raw.githubusercontent.com/rekthq/assets/main/images/logo.svg"/></a>, <img alt="logo" class="site-logo inv-asset" src="https://raw.githubusercontent.com/rekthq/assets/main/images/logo.svg"/>, <div class="hidden md:block"><nav><a class="nav-item" href="/termAndConditions">t&amp;c</a><span class="divider"></span><a class="nav-item" href="https://www.youtube.com/@RektNews./videos" rel="noopener noreferrer" target="_blank">videos</a><span class="divider"></span><a class="nav-item nav-item-active" href="/leaderboard">leaderboard</a><span class="divider"></span><a class="nav-item" href="/research">research</a><span class="divider"></span><button aria-expanded="false" aria-haspopup="menu" class="nav-item font-bold px-3 py-1 transition-colors duration-150 hover:bg-accent hover:text-accent-foreground focus:outline-none focus:bg-accent focus:text-accent-foreground rounded" data-state="closed" id="radix-:Rj4im:" style="background:none;border:none;cursor:pointer" type="button">tools</button><span class="divider"></span><div><div class="flex gap-2"><button class="text-xl md:text-[16px]">log in</button></div></div></nav></div>, <nav><a class="nav-item" href="/termAndConditions">t&amp;c</a><span class="divider"></span><a class="nav-item" href="https://www.youtube.com/@RektNews./videos" rel="noopener noreferrer" target="_blank">videos</a><span class="divider"></span><a class="nav-item nav-item-active" href="/leaderboard">leaderboard</a><span class="divider"></span><a class="nav-item" href="/research">research</a><span class="divider"></span><button aria-expanded="false" aria-haspopup="menu" class="nav-item font-bold px-3 py-1 transition-colors duration-150 hover:bg-accent hover:text-accent-foreground focus:outline-none focus:bg-accent focus:text-accent-foreground rounded" data-state="closed" id="radix-:Rj4im:" style="background:none;border:none;cursor:pointer" type="button">tools</button><span class="divider"></span><div><div class="flex gap-2"><button class="text-xl md:text-[16px]">log in</button></div></div></nav>, <a class="nav-item" href="/termAndConditions">t&amp;c</a>, <span class="divider"></span>, <a class="nav-item" href="https://www.youtube.com/@RektNews./videos" rel="noopener noreferrer" target="_blank">videos</a>, <span class="divider"></span>, <a class="nav-item nav-item-active" href="/leaderboard">leaderboard</a>, <span class="divider"></span>, <a class="nav-item" href="/research">research</a>, <span class="divider"></span>, <button aria-expanded="false" aria-haspopup="menu" class="nav-item font-bold px-3 py-1 transition-colors duration-150 hover:bg-accent hover:text-accent-foreground focus:outline-none focus:bg-accent focus:text-accent-foreground rounded" data-state="closed" id="radix-:Rj4im:" style="background:none;border:none;cursor:pointer" type="button">tools</button>, <span class="divider"></span>, <div><div class="flex gap-2"><button class="text-xl md:text-[16px]">log in</button></div></div>, <div class="flex gap-2"><button class="text-xl md:text-[16px]">log in</button></div>, <button class="text-xl md:text-[16px]">log in</button>, <div class="md:hidden flex gap-2 items-center"><div><div class="flex gap-2"><button class="text-xl md:text-[16px]">log in</button></div></div><span class="divider pr-2"></span><button aria-expanded="false" aria-haspopup="menu" data-state="closed" id="radix-:R7kim:" type="button"><svg class="w-8 h-8" fill="currentColor" height="1em" stroke="currentColor" stroke-width="0" viewbox="0 0 448 512" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path></svg></button></div>, <div><div class="flex gap-2"><button class="text-xl md:text-[16px]">log in</button></div></div>, <div class="flex gap-2"><button class="text-xl md:text-[16px]">log in</button></div>, <button class="text-xl md:text-[16px]">log in</button>, <span class="divider pr-2"></span>, <button aria-expanded="false" aria-haspopup="menu" data-state="closed" id="radix-:R7kim:" type="button"><svg class="w-8 h-8" fill="currentColor" height="1em" stroke="currentColor" stroke-width="0" viewbox="0 0 448 512" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path></svg></button>, <svg class="w-8 h-8" fill="currentColor" height="1em" stroke="currentColor" stroke-width="0" viewbox="0 0 448 512" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path></svg>, <path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path>]

In [10]:
text = soup.get_text()

In [11]:
print(soup.text)

Rekt - Leaderboardt&cvideosleaderboardresearchtoolslog inlog in1.The One That Got Away N/A$14,847,374,246 | 12/20/20202.ByBit - Rekt N/A$1,436,173,027 | 2/21/20253.Ronin Network - REKT Unaudited$624,000,000 | 03/23/20224.Poly Network - REKT Unaudited$611,000,000 | 08/10/20215.BNB Bridge - REKT Unaudited$586,000,000 | 10/06/20226.SBF - MASK OFF N/A$477,000,000 | 11/12/227.Wormhole - REKT Neodyme$326,000,000 | 02/02/20228.DMM Bitcoin - Rekt N/A$304,000,000 | 05/30/20249.WazirX - Rekt N/A$235,000,000 | 07/18/202410.Cetus - Rekt N/A$223,000,000 | 5/22/202511.Gala Games - Rekt Anchain, Certik$216,000,000 | 05/20/202412.Mixin Network - REKT N/A$200,000,000 | 09/23/202313.Euler Finance - REKT Sherlock$197,000,000 | 03/13/202314.BitMart - REKT N/A$196,000,000 | 12/04/202115.Nomad Bridge - REKT N/A$190,000,000 | 08/01/202216.Beanstalk - REKT Unaudited$181,000,000 | 04/17/202217.Wintermute - REKT 2 N/A$162,300,000 | 09/20/202218.Compound - REKT Unaudited$147,000,000 | 09/29/202119.Vulcan Forged - REKT Unaudited$140,000,000 | 12/13/202120.Cream Finance - REKT 2 Unaudited$130,000,000 | 10/27/202121.Balancer - Rekt II N/A$128,000,000 | 11/3/202522.Multichain - REKT 2 N/A$126,300,000 | 07/06/202323.Poloniex - REKT N/A$126,000,000 | 11/10/202324.BonqDAO - REKT Out of scope$120,000,000 | 02/01/202325.Badger - REKT Unaudited$120,000,000 | 12/02/202126.Mango Markets - REKT Out of Scope$115,000,000 | 10/11/202227.Atomic Wallet - REKT Unaudited$100,000,000 | 06/02/202328.Harmony Bridge - REKT N/A$100,000,000 | 06/23/202229.HECO Bridge, HTX - REKT N/A$99,100,000 | 11/22/202330.Mirror Protocol - REKT Unaudited$92,000,000 | 10/08/202131.Woofi - Rekt Certik$85,000,000 | 03/05/202432.Orbit Bridge - REKT Out of scope$81,500,000 | 12/31/202333.Fei Rari - REKT 2 Unaudited$80,000,000 | 05/01/202234.Qubit Finance - REKT Unaudited$80,000,000 | 01/28/202235.Ascendex - REKT Unaudited$77,700,000 | 12/12/202136.Phemex - Rekt N/A$73,540,297 | 01/23/202537.Curve, Vyper - REKT N/A$69,300,000 | 07/30/202338.Munchables - REKT Entersof$62,500,000 | 03/26/202439.AlphaPo - REKT N/A$60,000,000 | 07/22/202340.EasyFi - REKT Unaudited$59,000,000 | 04/19/202141.Uranium Finance - REKT Unaudited$57,200,000 | 04/28/202142.Whale Hunter's Payday N/A$55,470,000 | 08/20/202443.bZx - REKT Unaudited$55,000,000 | 11/05/202144.CoinEx - REKT N/A$54,300,000 | 09/12/202345.Radiant Capital - Rekt II N/A$53,000,000 | 10/16/202446.BTCTurk - Rekt N/A$51,700,000 | 8/14/202547.Infini - Rekt N/A$49,500,000 | 2/24/202448.KyberSwap - REKT ChainSecurity, Sherlock$48,000,000 | 11/22/202349.Cashio - REKT Unaudited$48,000,000 | 03/23/202250.PancakeBunny - REKT Unaudited$45,000,000 | 05/19/202151.Kucoin - REKT Internal audit$45,000,000 | 09/29/202052.BingX - Rekt N/A$44,700,000 | 09/19/202453.Hedgey Finance - Rekt Consensys Diligence$44,700,000 | 04/19/202454.CoinDCX - Rekt N/A$44,300,000 | 7/18/202555.GMX - Rekt N/A$42,000,000 | 7/9/202556.Stake - REKT N/A$41,600,000 | 09/04/202357.Swissborg - Rekt N/A$41,500,000 | 9/8/202558.UXLink - Rekt N/A$41,000,000 | 9/22/202559.Alpha Finance - REKT Quantstamp, Peckshield$37,500,000 | 02/13/202160.LastPass Users - REKT N/A$37,000,000 | 12/14/202261.Vee Finance - REKT Slowmist$34,000,000 | 09/21/202162.Crypto.com - REKT Deloitte$33,700,000 | 01/18/202263.ZKasino - Rekt Certik$33,000,000 | 04/20/202464.Meerkat Finance - BSC - REKT Unaudited$32,000,000 | 03/04/202165.MonoX - REKT Halborn, Peckshield$31,400,000 | 11/30/202166.Spartan Protocol - REKT N/A$30,500,000 | 05/02/202167.Grim Finance - REKT Solidity Finance$30,000,000 | 12/18/202168.Deribit - REKT N/A$28,000,000 | 11/01/202269.Wintermute - REKT N/A$27,600,000 | 06/05/202270.Step Finance - Rekt N/A$27,300,000 | 1/31/202671.BigONE - Rekt N/A$27,000,000 | 7/15/202572.Penpie - Rekt Watch Pug, Zokyo$27,000,000 | 09/03/202473.StableMagnet - REKT Techrate$27,000,000 | 06/23/202174.Paid Network - REKT Unaudited$27,000,000 | 03/05/202175.Truebit - Rekt N/A$26,200,000 | 1/8/202676.Kronos Research - REKT N/A$26,000,000 | 11/18/202377.Indodax - Rekt N/A$25,220,000 | 09/10/202478.Harvest Finance - REKT Haechi, Peckshield$25,000,000 | 10/26/202079.SBI Crypto - Rekt N/A$24,000,000 | 9/24/202580.Ankr & Helio - REKT N/A$24,000,000 | 12/02/202281.XToken - REKT Peckshield$24,000,000 | 05/12/202182.BALD on Base - REKT N/A$23,000,000 | 07/31/202383.Elephant Money - REKT Solidity Finance$22,200,000 | 04/12/202184.Blizz Finance, Venus Protocol - REKT n/a$21,800,000 | 05/13/202285.Transit Swap - REKT Out of scope$21,200,000 | 10/02/202286.Unizen - Rekt Halborn, Verichains$21,000,000 | 03/08/202487.Sonne Finance - Rekt yAudit$20,000,000 | 05/15/202488.Popsicle Finance - REKT Peckshield$20,000,000 | 08/03/202189.Pickle Finance - REKT Unaudited$19,700,000 | 11/22/202090.Uwulend - Rekt Peckshield$19,400,000 | 06/10/202491.Cream Finance - REKT Unaudited$18,800,000 | 08/30/202192.Snowdog - REKT Unaudited$18,100,000 | 11/25/202193.bEarn - REKT Unaudited$18,000,000 | 05/17/202194.AlexLab - Rekt II N/A$16,180,000 | 6/6/202595.Curio - REKT N/A$16,000,000 | 03/23/202496.Indexed Finance - REKT Unaudited$16,000,000 | 10/14/202196.Team Finance - REKT Zokyo Security$15,800,000 | 10/27/202297.Inverse Finance - REKT Unaudited$15,600,000 | 04/02/202298.Eminence - Rekt in prod Unaudited$15,000,000 | 09/28/202099.Woo X - Rekt N/A$14,000,000 | 7/24/2025100.Furucombo - REKT Unaudited$14,000,000 | 02/27/2021101.M2 Exchange - Rekt N/A$13,700,000 | 10/31/2024102.Deus DAO - REKT 2 Armor Labs$13,400,000 | 04/28/2022103.Abracadabra - Rekt II Guardian Audits$12,913,691 | 3/25/2025104.Cork Protocol - Rekt N/A$12,000,000 | 5/28/2025105.Ronin Network - Rekt II Unaudited$12,000,000 | 08/07/2024106.Compounder Finance - REKT out of scope$12,000,000 | 12/02/2020107.Agave DAO, Hundred Finance - REKT Unaudited$11,700,000 | 03/15/2022108.PrismaFi - REKT PrismaFi$11,600,000 | 03/28/2024109.Yearn - REKT 2 Unaudited$11,400,000 | 04/13/2023110.Saddle Finance - REKT 2 Unaudited$11,000,000 | 12/02/2021111.Value DeFi - REKT 3 Unaudited$11,000,000 | 05/07/2021112.Yearn - REKT Unaudited$11,000,000 | 02/05/2021113.Yieldblox - Rekt N/A$10,970,000 | 2/22/2026114.Dego Finance - REKT Peckshield$10,000,000 | 02/10/2022115.Arbix Finance - REKT Certik$10,000,000 | 01/04/2022116.Rari Capital - REKT Quantstamp$10,000,000 | 05/08/2021117.Value DeFi - REKT 2 Unaudited$10,000,000 | 05/05/2021118.ResupplyFi - Rekt ChainSecurity, Electi$9,800,000 | 6/25/2025119.LiFi/Jumper - Rekt n/a$9,730,000 | 07/16/2024120.zkLend - Rekt N/A$9,570,000 | 02/11/2025121.Cover - REKT Arcadia Group$9,400,000 | 12/29/2020122.Yearn - Rekt III N/A$9,000,000 | 11/30/2025123.dYdX - REKT N/A$9,000,000 | 11/18/2023124.Punk Protocol - REKT Unaudited$8,950,000 | 08/10/2021125.Safemoon - REKT Unaudited$8,900,000 | 03/28/2023126.Crema Finance - REKT Bramah Systems$8,800,000 | 07/02/2022127.Polter Finance Unaudited$8,700,000 | 11/16/2024128.Superfluid - REKT Peckshield$8,700,000 | 02/08/2022129.Platypus Finance - REKT Unaudited$8,500,000 | 02/17/2023130.Bunni - Rekt N/A$8,400,000 | 9/1/2025131.Zoth - Rekt N/A$8,400,000 | 3/21/2025132.Moola Market - REKT N/A$8,400,000 | 10/19/2022133.Visor Finance - REKT Unaudited$8,200,000 | 12/21/2021134.Bittensor - Rekt N/A$8,000,000 | 07/02/2024135.THORChain - REKT 2 THORChain$8,000,000 | 07/22/2021136.Hack Epidemic (Origin Protocol - REKT) Unaudited$8,000,000 | 11/17/2020137.LCX - REKT Unaudited$7,940,000 | 01/08/2022138.HTX (Huobi) - REKT N/A$7,900,000 | 09/24/2023139.Anyswap - REKT Unaudited$7,900,000 | 07/10/2021140.Warp Finance - REKT Hacken$7,800,000 | 12/18/2020141.Meter - REKT Unaudited$7,700,000 | 02/06/2022142.Rho Market - Rekt N/A$7,500,000 | 07/19/2024143.Nightmare on FTM Street N/A$7,500,000 | 10/17/2023144.Jimbo's Protocol - REKT Unaudited$7,500,000 | 05/28/2023145.KiloEx - Rekt N/A$7,491,500 | 4/14/2025146.Hundred Finance - REKT 2 WhiteHatDAO$7,400,000 | 04/15/2023147.Exactly Protocol - REKT Out of scope$7,200,000 | 08/18/2023148.BurgerSwap - REKT Unaudited$7,200,000 | 05/28/2021149.Saga - Rekt N/A$7,000,000 | 1/21/2026150.Odin.Fun - Rekt N/A$7,000,000 | 8/12/2025151.Value DeFi - REKT Unaudited$7,000,000 | 11/14/2020152.Ionic Money - Rekt N/A$6,943,774 | 02/4/2025153.Velocore - Rekt Zokyo, Hacken, Scalebit$6,800,000 | 06/02/2024154.Abracadabra - REKT Unaudited$6,500,000 | 01/30/2024155.Deus DAO - R3KT Unaudited$6,500,000 | 05/05/2023156.Lodestar Finance - REKT Unaudited$6,500,000 | 12/10/2022157.Alchemix - REKT Unaudited$6,500,000 | 06/16/2021158.Astroport - Rekt N/A$6,400,000 | 07/30/2024159.Seneca Protocol - REKT Halborn$6,400,000 | 02/28/2024160.Belt - REKT Haechi$6,300,000 | 05/29/2021161.Audius - REKT Kudelski, OpenZeppelin$6,000,000 | 07/23/2022162.DeltaPrime - Rekt N/A$5,980,000 | 09/15/2024163.Bondly - REKT Unaudited$5,900,000 | 07/15/2021164.Loopscale - Rekt N/A$5,800,000 | 4/26/2025165.Inverse Finance - REKT 2 Unaudited$5,800,000 | 06/16/2022166.Roll - REKT Unaudited$5,700,000 | 03/14/2021167.An Un-SOL-ved Mystery N/A$5,300,000 | 08/02/2022168.BetterBank - Rekt Out of Scope$5,000,000 | 8/26/2025169.1Inch - Rekt N/A$5,000,000 | 3/5/2025170.THORChain - REKT Unaudited$5,000,000 | 07/15/2021171.Shezmu - Rekt N/A$4,900,000 | 09/20/2024172.DeltaPrime - Rekt II Peckshield$4,850,000 | 11/11/2024173.Super Sushi Samurai - REKT Verichains$4,800,000 | 03/21/2024174.Credix - Rekt N/A$4,500,000 | 8/4/2025175.Gamma Strategies - REKT Out of scope$4,500,000 | 01/04/2024176.Radiant Capital - REKT Out of scope$4,500,000 | 01/02/2024177.X-Token - REKT X2 Unaudited$4,500,000 | 08/29/2021178.Eleven Finance - REKT Unaudited$4,500,000 | 06/22/2021179.IoTeX - Rekt N/A$4,400,000 | 2/21/2025180.Tapioca DAO - Rekt N/A$4,400,000 | 10/18/2024181.Poly Network - REKT 2 N/A$4,400,000 | 07/01/2023182.Raydium - REKT N/A$4,400,000 | 12/16/2022183.ChainSwap - REKT Unaudited$4,400,000 | 07/11/2021184.AlexLab - Rekt CoinFabrik$4,300,000 | 05/14/2024185.Conic Finance - REKT Out of scope$4,200,000 | 07/21/2023186.Makina - Rekt N/A$4,130,000 | 1/20/2026187.Kokomo Finance - REKT Unaudited$4,000,000 | 03/26/2023188.Voltage Finance - REKT Unaudited$4,000,000 | 03/31/2022189.DAO Maker - REKT TBC$4,000,000 | 09/04/2021190.Onyx Protocol - Rekt II CertiK$3,800,000 | 09/25/2024191.Force Bridge - Rekt N/A$3,760,000 | 6/1/2025191.dForce Network - REKT Out of scope$3,650,000 | 02/09/2023192.ArcadiaFi - Rekt Pashov Audit Group$3,600,000 | 7/15/2025193.Nirvana Finance - REKT Sec3 Auto Audit Software$3,500,000 | 07/28/2022194.EraLend - REKT Out of scope$3,400,000 | 07/25/2023195.Socket - REKT Out of scope$3,300,000 | 01/16/2024196.Raft - REKT Trail of Bits, Hats Finance$3,300,000 | 11/10/2023197.SushiSwap - REKT Unaudited$3,300,000 | 04/09/2023198.Skyward Finance - REKT Unaudited$3,200,000 | 11/02/2022199.GANA Payment - Rekt N/A$3,100,000 | 11/20/2025200.JayPegs Automart - REKT Unaudited$3,100,000 | 09/17/2021201.GriffinAI - Rekt N/A$3,000,000 | 9/24/2025202.Shibarium - Rekt N/A$3,000,000 | 9/12/2025203.Banana Gun - Rekt N/A$3,000,000 | 09/19/2024204.Certik/Kraken - Rekt N/A$3,000,000 | 06/09/2024205.Swaprum - REKT Out of scope$3,000,000 | 05/18/2023206.Orion Protocol - REKT Unaudited$3,000,000 | 02/02/2023207.Fortress Protocol - REKT Hash0x, EtherAuthority$3,000,000 | 05/08/2022208.Deus DAO - REKT Unaudited$3,000,000 | 03/15/2021209.Stars Arena - REKT Unaudited$2,900,000 | 10/07/2023210.Lucky Star Currency, FSL - REKT Unaudited$2,790,000 | 10/09/2023211.Aevo - Rekt N/A$2,700,000 | 12/12/2025212.OKX DEX - REKT N/A$2,700,000 | 12/12/2023213.Remitano - REKT N/A$2,700,000 | 09/14/2023214.Shibarium Bridge - REKT N/A$2,600,000 | 08/17/2023215.Atlantis Loans - REKT Unaudited$2,500,000 | 06/10/2023216.PancakeBunny - REKT 2 Unaudited$2,400,000 | 07/16/2021217.TempleDAO - REKT Unaudited$2,300,000 | 10/11/2022218.Platypus Finance - REKT 2 Out of scope$2,200,000 | 10/12/2023219.MobiusDAO - Rekt N/A$2,150,000 | 5/11/2025220.ETHTrustFund - Rekt N/A$2,100,000 | 07/20/2024221.Onyx Protocol - REKT N/A$2,100,000 | 11/01/2023222.Balancer - REKT Out of scope$2,100,000 | 08/27/2023223.Zunami Protocol - REKT Hashex$2,100,000 | 08/13/2023224.Kannagi Finance - REKT Out of scope$2,100,000 | 07/29/2023225.Gym Network - REKT Out of scope$2,100,000 | 06/08/2022226.Revest Finance - REKT Solidity Finance$2,010,000 | 03/27/2022227.New Gold Protocol - Rekt N/A$2,000,000 | 9/17/2025228.Bedrock - Rekt N/A$2,000,000 | 09/25/2024229.Grand Base - REKT Unaudited$2,000,000 | 04/15/2024230.RIP MEV Bot 2 N/A$2,000,000 | 11/07/2023231.Dexible - REKT Unaudited$2,000,000 | 02/17/2023232.MM Finance - REKT Unaudited$2,000,000 | 05/04/2022233.DODO - REKT Unaudited$2,000,000 | 03/09/2021234.Akropolis - REKT CertiK, SmartDec$2,000,000 | 11/12/2020235.GemPad - Rekt ContractWolf$1,900,000 | 12/17/2024236.Pike Finance - Rekt unaudited$1,900,000 | 04/30/2024237.Hope Finance - REKT AuditRateTech, Cognitos$1,860,000 | 02/20/2023238.Merlin DEX - REKT Certik$1,820,000 | 04/25/2023239.Abracadabra - Rekt III N/A$1,800,000 | 10/04/2025240.Moonwell - Rekt N/A$1,780,000 | 2/15/2026241.Bent Finance - REKT Unaudited$1,750,000 | 12/21/2021242.8ight Finance - REKT Unaudited$1,750,000 | 12/08/2021243.DeFiLabs - REKT Out of scope$1,600,000 | 07/27/2023244.Acala Network - REKT Out of scope$1,600,000 | 08/13/2021245.RIP MEV BOT N/A$1,500,000 | 09/27/2022246.Levyathan - REKT Unaudited$1,500,000 | 07/30/2021247.TMXTribe - Rekt N/A$1,400,000 | 1/5/2026248.Treasure DAO - REKT Unaudited$1,400,000 | 03/03/2022249.Money for nothing? N/A$1,300,000 | 12/26/2023250.The Big Combo (Growth DeFi - REKT) Consensys Dilligence$1,300,000 | 02/09/2021251.LNDFi - Rekt N/A$1,180,000 | 5/9/2021252.Levana Protocol - REKT Out of scope$1,146,000 | 12/13/2023253.Steadefi - REKT N/A$1,140,000 | 08/07/2023254.Sovryn - REKT Unaudited$1,111,000 | 10/04/2022255.BrincFi - Rekt Cold Case N/A$1,100,000 | 12/14/2021256.Level Finance - REKT Obelisk$1,100,000 | 05/01/2023257.Moby Trade - Rekt N/A$1,003,080 | 1/8/2025258.USPD - Rekt N/A$1,000,000 | 12/4/2025259.RocketSwap - REKT N/A$869,000 | 08/14/2023260.Orange Finance - Rekt N/A$843,500 | 1/7/2024261.Sturdy Finance - REKT Out of scope$800,000 | 06/12/2023262.Tornado Cash Governance - REKT Unaudited$750,000 | 05/20/2023263.Autoshark - REKT Techrate$745,000 | 05/24/2021264.Merlin Labs - REKT Hacken$680,000 | 05/26/2021265.Midas Capital - REKT Out of scope$660,000 | 01/15/2023266.Unibot - REKT Unaudited$640,000 | 10/31/2023267.Midas Capital - REKT 2 Out of scope$600,000 | 06/17/2023268.Curve Finance - REKT N/A$575,000 | 08/09/2022269.Drained By Design N/A$550,000 | 8/13/2025270.Merlin Labs - REKT 2 Unaudited$550,000 | 05/26/2021271.Hedera - REKT FP Complete$515,000 | 03/09/2023272.Zunami Protocol - Rekt II N/A$500,000 | 5/14/2025273.Clober Dex - Rekt Kupia Security$500,000 | 12/10/2024274.Zero To Lend N/A$371,000 | 2/23/2025275.SIR Trading - Rekt Egis Security$355,000 | 3/30/2025276.Merlin Labs - R3KT Unaudited$330,000 | 06/29/2021277.The Idols NFT - Rekt N/A$324,015 | 1/14/2025278.Yearn - Rekt IV N/A$293,000 | 12/16/2025279.Saddle Finance - REKT Openzeppelin, Certik, Quantstamp$275,735 | 01/20/2021280.SafeDollar - REKT Unaudited$248,000 | 06/28/2021281.Hypr Network - REKT Unaudited$220,000 | 12/13/2023282.Hacken - Rekt N/A$170,000 | 6/20/2025here lie the names of some of the defi protocols that have fallen victim to attack, exploit or arbitrage. this list is not complete and it never will be. these protocols are listed with respect; we appreciate and understand the work that lies behind each name.SUBSCRIBEall content copyright rekt © 2026 • all rights reserved.donate (ETH/ERC20):0x3C5c2F4bCeC51a36494682f91Dbc6cA7c63B514Crun by RektHQ. founded by Julien Bouteloup

In [12]:
soup.find_all("a")

[<a href="/"><img alt="logo" class="site-logo inv-asset" src="https://raw.githubusercontent.com/rekthq/assets/main/images/logo.svg"/></a>,
 <a class="nav-item" href="/termAndConditions">t&amp;c</a>,
 <a class="nav-item" href="https://www.youtube.com/@RektNews./videos" rel="noopener noreferrer" target="_blank">videos</a>,
 <a class="nav-item nav-item-active" href="/leaderboard">leaderboard</a>,
 <a class="nav-item" href="/research">research</a>,
 <a href="/the-one-that-got-away">The One That Got Away<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/bybit-rekt">ByBit - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/ronin-rekt">Ronin Network - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/polynetwork-rekt">Poly Network - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/bnb-bridge-rekt">BNB Bridge - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/sbf-mask-off">SBF - MASK OFF<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/wormhole-rekt">Wormhole - REKT<!-- --> <span class="leaderboard-audit">Neodyme</span></a>,
 <a href="/dmm-rekt">DMM Bitcoin - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/wazirx-rekt">WazirX - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/cetus-rekt">Cetus - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/gala-games-rekt">Gala Games - Rekt<!-- --> <span class="leaderboard-audit">Anchain, Certik</span></a>,
 <a href="/mixin-rekt">Mixin Network - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/euler-rekt">Euler Finance - REKT<!-- --> <span class="leaderboard-audit">Sherlock</span></a>,
 <a href="/bitmart-rekt">BitMart - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/nomad-rekt">Nomad Bridge - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/beanstalk-rekt">Beanstalk - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/wintermute-rekt-2">Wintermute - REKT 2<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/compound-rekt">Compound - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/vulcan-forged-rekt">Vulcan Forged - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/cream-rekt-2">Cream Finance - REKT 2<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/balancer-rekt2">Balancer - Rekt II<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/multichain-rekt2">Multichain - REKT 2<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/poloniex-rekt">Poloniex - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/bonq-rekt">BonqDAO - REKT<!-- --> <span class="leaderboard-audit">Out of scope</span></a>,
 <a href="/badger-rekt">Badger - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/mango-markets-rekt">Mango Markets - REKT<!-- --> <span class="leaderboard-audit">Out of Scope</span></a>,
 <a href="/atomic-wallet-rekt">Atomic Wallet - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/harmony-rekt">Harmony Bridge - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/heco-htx-rekt">HECO Bridge, HTX - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/mirror-rekt">Mirror Protocol - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/woo-rekt">Woofi - Rekt<!-- --> <span class="leaderboard-audit">Certik</span></a>,
 <a href="/orbit-bridge-rekt">Orbit Bridge - REKT<!-- --> <span class="leaderboard-audit">Out of scope</span></a>,
 <a href="/fei-rari-rekt">Fei Rari - REKT 2<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/qubit-rekt">Qubit Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/ascendex-rekt">Ascendex - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/phemex-rekt">Phemex - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/curve-vyper-rekt">Curve, Vyper - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/munchables-rekt">Munchables - REKT<!-- --> <span class="leaderboard-audit">Entersof</span></a>,
 <a href="/alphapo-rekt">AlphaPo - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/easyfi-rekt">EasyFi - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/uranium-rekt">Uranium Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/whale-hunters-payday">Whale Hunter's Payday<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/bzx-rekt">bZx - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/coinex-rekt">CoinEx - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/radiant-capital-rekt2">Radiant Capital - Rekt II<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/btcturk-rekt">BTCTurk - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/infini-rekt">Infini - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/kyberswap-rekt">KyberSwap - REKT<!-- --> <span class="leaderboard-audit">ChainSecurity, Sherlock</span></a>,
 <a href="/cashio-rekt">Cashio - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/pancakebunny-rekt">PancakeBunny - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/epic-hack-homie">Kucoin - REKT<!-- --> <span class="leaderboard-audit">Internal audit</span></a>,
 <a href="/bingx-rekt">BingX - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/hedgey-finance-rekt">Hedgey Finance - Rekt<!-- --> <span class="leaderboard-audit">Consensys Diligence</span></a>,
 <a href="/coindcx-rekt">CoinDCX - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/gmx-rekt">GMX - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/stake-rekt">Stake - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/swissborg-rekt">Swissborg - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/uxlink-rekt">UXLink - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/alpha-finance-rekt">Alpha Finance - REKT<!-- --> <span class="leaderboard-audit">Quantstamp, Peckshield</span></a>,
 <a href="/lastpass-users-rekt">LastPass Users - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/veefinance-rekt">Vee Finance - REKT<!-- --> <span class="leaderboard-audit">Slowmist</span></a>,
 <a href="/cryptocom-rekt">Crypto.com - REKT<!-- --> <span class="leaderboard-audit">Deloitte</span></a>,
 <a href="/zkasino-rekt">ZKasino - Rekt<!-- --> <span class="leaderboard-audit">Certik</span></a>,
 <a href="/meerkat-finance-bsc-rekt">Meerkat Finance - BSC - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/monox-rekt">MonoX - REKT<!-- --> <span class="leaderboard-audit">Halborn, Peckshield</span></a>,
 <a href="/spartan-rekt">Spartan Protocol - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/grim-finance-rekt">Grim Finance - REKT<!-- --> <span class="leaderboard-audit">Solidity Finance</span></a>,
 <a href="/deribit-rekt">Deribit - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/wintermute-rekt">Wintermute - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/step-finance-rekt">Step Finance - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/bigone-rekt">BigONE - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/penpie-rekt">Penpie - Rekt<!-- --> <span class="leaderboard-audit">Watch Pug, Zokyo</span></a>,
 <a href="/stablemagnet-rekt">StableMagnet - REKT<!-- --> <span class="leaderboard-audit">Techrate</span></a>,
 <a href="/paid-rekt">Paid Network - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/truebit-rekt">Truebit - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/kronos-rekt">Kronos Research - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/indodax-rekt">Indodax - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/harvest-finance-rekt">Harvest Finance - REKT<!-- --> <span class="leaderboard-audit">Haechi, Peckshield</span></a>,
 <a href="/sbi-crypto-rekt">SBI Crypto - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/ankr-helio-rekt">Ankr &amp; Helio - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/xtoken-rekt">XToken - REKT<!-- --> <span class="leaderboard-audit">Peckshield</span></a>,
 <a href="/bald-rekt">BALD on Base - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/elephant-money-rekt">Elephant Money - REKT<!-- --> <span class="leaderboard-audit">Solidity Finance</span></a>,
 <a href="/venus-blizz-rekt">Blizz Finance, Venus Protocol - REKT<!-- --> <span class="leaderboard-audit">n/a</span></a>,
 <a href="/transit-swap-rekt">Transit Swap - REKT<!-- --> <span class="leaderboard-audit">Out of scope</span></a>,
 <a href="/unizen-rekt">Unizen - Rekt<!-- --> <span class="leaderboard-audit">Halborn, Verichains</span></a>,
 <a href="/sonne-finance-rekt">Sonne Finance - Rekt<!-- --> <span class="leaderboard-audit">yAudit</span></a>,
 <a href="/popsicle-rekt">Popsicle Finance - REKT<!-- --> <span class="leaderboard-audit">Peckshield</span></a>,
 <a href="/pickle-finance-rekt">Pickle Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/uwulend-rekt">Uwulend - Rekt<!-- --> <span class="leaderboard-audit">Peckshield</span></a>,
 <a href="/cream-rekt">Cream Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/snowdog-rekt">Snowdog - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/bearn-rekt">bEarn - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/alexlab-rekt2">AlexLab - Rekt II<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/curio-rekt">Curio - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/indexed-finance-rekt">Indexed Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/teamfinance-rekt">Team Finance - REKT<!-- --> <span class="leaderboard-audit">Zokyo Security</span></a>,
 <a href="/inverse-finance-rekt">Inverse Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/eminence-rekt-in-prod">Eminence - Rekt in prod<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/woox-rekt">Woo X - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/furucombo-rekt">Furucombo - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/m2-exchange-rekt">M2 Exchange - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/deus-dao-rekt-2">Deus DAO - REKT 2<!-- --> <span class="leaderboard-audit">Armor Labs</span></a>,
 <a href="/abracadabra-rekt2">Abracadabra - Rekt II<!-- --> <span class="leaderboard-audit">Guardian Audits</span></a>,
 <a href="/cork-protocol-rekt">Cork Protocol - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/roninnetwork-rektII">Ronin Network - Rekt II<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/deathbed-confessions-c3pr">Compounder Finance - REKT<!-- --> <span class="leaderboard-audit">out of scope</span></a>,
 <a href="/agave-hundred-rekt">Agave DAO, Hundred Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/prismafi-rekt">PrismaFi - REKT<!-- --> <span class="leaderboard-audit">PrismaFi</span></a>,
 <a href="/yearn2-rekt">Yearn - REKT 2<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/saddle-finance-rekt2">Saddle Finance - REKT 2<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/value-rekt3">Value DeFi - REKT 3<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/yearn-rekt">Yearn - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/yieldblox-rekt">Yieldblox - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/dego-finance-rekt">Dego Finance - REKT<!-- --> <span class="leaderboard-audit">Peckshield</span></a>,
 <a href="/arbix-rekt">Arbix Finance - REKT<!-- --> <span class="leaderboard-audit">Certik</span></a>,
 <a href="/rari-capital-rekt">Rari Capital - REKT<!-- --> <span class="leaderboard-audit">Quantstamp</span></a>,
 <a href="/value-rekt2">Value DeFi - REKT 2<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/resupplyfi-rekt">ResupplyFi - Rekt<!-- --> <span class="leaderboard-audit">ChainSecurity, Electi</span></a>,
 <a href="/lifi-jumper-rekt">LiFi/Jumper - Rekt<!-- --> <span class="leaderboard-audit">n/a</span></a>,
 <a href="/zklend-rekt">zkLend - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/cover-rekt">Cover - REKT<!-- --> <span class="leaderboard-audit">Arcadia Group</span></a>,
 <a href="/yearn-rekt3">Yearn - Rekt III<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/dydx-rekt">dYdX - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/punkprotocol-rekt">Punk Protocol - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/safemoon-rekt">Safemoon - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/crema-finance-rekt">Crema Finance - REKT<!-- --> <span class="leaderboard-audit">Bramah Systems</span></a>,
 <a href="/polter-finance-rekt">Polter Finance<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/superfluid-rekt">Superfluid - REKT<!-- --> <span class="leaderboard-audit">Peckshield</span></a>,
 <a href="/platypus-finance-rekt">Platypus Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/bunni-rekt">Bunni - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/zoth-rekt">Zoth - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/moola-markets-rekt">Moola Market - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/visor-finance-rekt">Visor Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/bittensor-rekt">Bittensor - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/thorchain-rekt2">THORChain - REKT 2<!-- --> <span class="leaderboard-audit">THORChain</span></a>,
 <a href="/hack-epidemic">Hack Epidemic (Origin Protocol - REKT)<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/lcx-rekt">LCX - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/htx-huobi-rekt">HTX (Huobi) - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/anyswap-rekt">Anyswap - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/warp-finance-rekt">Warp Finance - REKT<!-- --> <span class="leaderboard-audit">Hacken</span></a>,
 <a href="/meter-rekt">Meter - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/rho-market-rekt">Rho Market - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/nightmare-ftm">Nightmare on FTM Street<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/jimbo-rekt">Jimbo's Protocol - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/kiloex-rekt">KiloEx - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/hundred-rekt2">Hundred Finance - REKT 2<!-- --> <span class="leaderboard-audit">WhiteHatDAO</span></a>,
 <a href="/exactly-protocol-rekt">Exactly Protocol - REKT<!-- --> <span class="leaderboard-audit">Out of scope</span></a>,
 <a href="/burgerswap-rekt">BurgerSwap - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/saga-rekt">Saga - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/odin-fun-rekt">Odin.Fun - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/value-defi-rekt">Value DeFi - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/ionic-money-rekt">Ionic Money - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/velocore-rekt">Velocore - Rekt<!-- --> <span class="leaderboard-audit">Zokyo, Hacken, Scalebit</span></a>,
 <a href="/abra-rekt">Abracadabra - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/deus-dao-r3kt">Deus DAO - R3KT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/lodestar-rekt">Lodestar Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/alchemix-rekt">Alchemix - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/astroport-rekt">Astroport - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/seneca-protocol-rekt">Seneca Protocol - REKT<!-- --> <span class="leaderboard-audit">Halborn</span></a>,
 <a href="/belt-rekt">Belt - REKT<!-- --> <span class="leaderboard-audit">Haechi</span></a>,
 <a href="/audius-rekt">Audius - REKT<!-- --> <span class="leaderboard-audit">Kudelski, OpenZeppelin</span></a>,
 <a href="/deltaprime-rekt">DeltaPrime - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/bondly-rekt">Bondly - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/loopscale-rekt">Loopscale - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/inverse-rekt2">Inverse Finance - REKT 2<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/roll-rekt">Roll - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/unsolved-mystery">An Un-SOL-ved Mystery<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/betterbank-rekt">BetterBank - Rekt<!-- --> <span class="leaderboard-audit">Out of Scope</span></a>,
 <a href="/1inch-rekt">1Inch - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/thorchain-rekt">THORChain - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/shezmu-rekt">Shezmu - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/deltaprime-rekt2">DeltaPrime - Rekt II<!-- --> <span class="leaderboard-audit">Peckshield</span></a>,
 <a href="/sss-rekt">Super Sushi Samurai - REKT<!-- --> <span class="leaderboard-audit">Verichains</span></a>,
 <a href="/credix-rekt">Credix - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/gamma-strategies-rekt">Gamma Strategies - REKT<!-- --> <span class="leaderboard-audit">Out of scope</span></a>,
 <a href="/radiant-capital-rekt">Radiant Capital - REKT<!-- --> <span class="leaderboard-audit">Out of scope</span></a>,
 <a href="/xtoken-rekt-x2">X-Token - REKT X2<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/11-rekt">Eleven Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,
 <a href="/iotex-rekt">IoTeX - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/tapioca-dao-rekt">Tapioca DAO - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/poly-network-rekt2">Poly Network - REKT 2<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/raydium-rekt">Raydium - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a>,
 <a href="/chainswap-rekt">ChainSwap - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a>,

In [13]:
# find all the anchor tags with "href" 
# attribute starting with "/"
exp_list=[]
for link in soup.find_all('a', 
                          attrs={'href': re.compile("^/")}):
    
    # display the actual urls
    content=link.get('href')
    
    clean_content=content.split('/')
    
    # Remove multiple null String elements twice
    #clean_content.remove('')
    #clean_content.remove('')
    
    # Remove all incapusulating list brackets from list elements
    new_list =(','.join(clean_content))
    
    exp_list.append(new_list)

In [14]:
exp_list[:5]

[',',
 ',termAndConditions',
 ',leaderboard',
 ',research',
 ',the-one-that-got-away']

In [15]:
# Testing for any more null elements 
#exp_list.remove('')

In [16]:
# Remove the rekt extension that is attached to protocol name
ext = '-rekt'
exp_list = [elem.replace(ext, '') for elem in exp_list]
exp_list = [elem.replace('-', '') for elem in exp_list]
exp_list = [elem.replace('leaderboard', '') for elem in exp_list]


print(exp_list)

[',', ',termAndConditions', ',', ',research', ',theonethatgotaway', ',bybit', ',ronin', ',polynetwork', ',bnbbridge', ',sbfmaskoff', ',wormhole', ',dmm', ',wazirx', ',cetus', ',galagames', ',mixin', ',euler', ',bitmart', ',nomad', ',beanstalk', ',wintermute2', ',compound', ',vulcanforged', ',cream2', ',balancer2', ',multichain2', ',poloniex', ',bonq', ',badger', ',mangomarkets', ',atomicwallet', ',harmony', ',hecohtx', ',mirror', ',woo', ',orbitbridge', ',feirari', ',qubit', ',ascendex', ',phemex', ',curvevyper', ',munchables', ',alphapo', ',easyfi', ',uranium', ',whalehunterspayday', ',bzx', ',coinex', ',radiantcapital2', ',btcturk', ',infini', ',kyberswap', ',cashio', ',pancakebunny', ',epichackhomie', ',bingx', ',hedgeyfinance', ',coindcx', ',gmx', ',stake', ',swissborg', ',uxlink', ',alphafinance', ',lastpassusers', ',veefinance', ',cryptocom', ',zkasino', ',meerkatfinancebsc', ',monox', ',spartan', ',grimfinance', ',deribit', ',wintermute', ',stepfinance', ',bigone', ',penpie', ',stablemagnet', ',paid', ',truebit', ',kronos', ',indodax', ',harvestfinance', ',sbicrypto', ',ankrhelio', ',xtoken', ',bald', ',elephantmoney', ',venusblizz', ',transitswap', ',unizen', ',sonnefinance', ',popsicle', ',picklefinance', ',uwulend', ',cream', ',snowdog', ',bearn', ',alexlab2', ',curio', ',indexedfinance', ',teamfinance', ',inversefinance', ',eminenceinprod', ',woox', ',furucombo', ',m2exchange', ',deusdao2', ',abracadabra2', ',corkprotocol', ',roninnetworkII', ',deathbedconfessionsc3pr', ',agavehundred', ',prismafi', ',yearn2', ',saddlefinance2', ',value3', ',yearn', ',yieldblox', ',degofinance', ',arbix', ',raricapital', ',value2', ',resupplyfi', ',lifijumper', ',zklend', ',cover', ',yearn3', ',dydx', ',punkprotocol', ',safemoon', ',cremafinance', ',polterfinance', ',superfluid', ',platypusfinance', ',bunni', ',zoth', ',moolamarkets', ',visorfinance', ',bittensor', ',thorchain2', ',hackepidemic', ',lcx', ',htxhuobi', ',anyswap', ',warpfinance', ',meter', ',rhomarket', ',nightmareftm', ',jimbo', ',kiloex', ',hundred2', ',exactlyprotocol', ',burgerswap', ',saga', ',odinfun', ',valuedefi', ',ionicmoney', ',velocore', ',abra', ',deusdaor3kt', ',lodestar', ',alchemix', ',astroport', ',senecaprotocol', ',belt', ',audius', ',deltaprime', ',bondly', ',loopscale', ',inverse2', ',roll', ',unsolvedmystery', ',betterbank', ',1inch', ',thorchain', ',shezmu', ',deltaprime2', ',sss', ',credix', ',gammastrategies', ',radiantcapital', ',xtokenx2', ',11', ',iotex', ',tapiocadao', ',polynetwork2', ',raydium', ',chainswap', ',alexlab', ',conicfinance', ',makina', ',kokomofinance', ',voltagefinance', ',daomaker', ',onyxprotocol2', ',forcebridge', ',dforcenetwork', ',arcadiafi', ',nirvana', ',eralend', ',socket', ',raft', ',sushiyoink', ',skyward', ',ganapayment', ',jaypegsautomart', ',griffinai', ',shibarium', ',bananagun', ',certikkraken', ',swaprum', ',orionprotocol', ',fortress', ',deusdao', ',starsarena', ',LSCFSL', ',aevo', ',okxdex', ',remitano', ',shibariumbridge', ',atlantisloans', ',pancakebunny2', ',templedao', ',platypus2', ',mobiusdao', ',ethtrustfund', ',onyxprotocol', ',balancer', ',zunamiprotocol', ',kannagifinance', ',gymnet', ',revestfinance', ',newgoldprotocol', ',bedrock', ',grandbase', ',ripmevbot2', ',dexible', ',madmeerkatfinance', ',audodo', ',akropolis', ',gempad', ',pike', ',hopefinance', ',merlindex', ',abracadabra3', ',moonwell', ',bentfinance', ',8ightfinance', ',defilabs', ',acalanetwork', ',ripmevbot', ',levyathan', ',tmztribe', ',treasuredao', ',moneyfornothing', ',thebigcombo', ',LNDFi', ',levana', ',steadefi', ',sovryn', ',brincficoldcase', ',levelfinance', ',mobytrade', ',uspd', ',rocketswap', ',orangefinance', ',sturdy', ',tornadogov', ',autoshark', ',merlinlabs', ',midascapital', ',unibot', ',midas2', ',curvefinance', ',drainedbydesign', ',merlin2', ',hedera', ',zunamiprotocol2', ',cloberdex', ',zerotolend', ',sirtrading', ',merlin3', ',theidolsnft', ',yearn4', ',saddlefinance', ',safedollar', ',hyprnetwork', ',hacken', ',']

In [17]:
exp_list[:5]

[',', ',termAndConditions', ',', ',research', ',theonethatgotaway']

In [18]:
del exp_list[0:5]

In [19]:
exp_list[:5]

[',bybit', ',ronin', ',polynetwork', ',bnbbridge', ',sbfmaskoff']

In [20]:
#exp_list.remove("' ")

In [21]:
# Final test
#exp_list.remove('')

In [22]:
len(exp_list)

284

### Search for Dates and amount_lost within list elements
After using the website inspector shortcut we were able to sift throught the HTML file for rekt.news and find that all dates and amounts were concatenated together within list elements.

In [23]:
from datetime import datetime
from dateutil import parser
import dateutil.parser as dparser

In [24]:
# li is the html tag for list elements within a table 
list_elements = soup.find_all("li")

list_elements

[<li><div class="leaderboard-row"><span class="leaderboard-index-l">1<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/the-one-that-got-away">The One That Got Away<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->14,847,374,246<!-- --> | <!-- -->12/20/2020</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index-l">2<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/bybit-rekt">ByBit - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->1,436,173,027<!-- --> | <!-- -->2/21/2025</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index-l">3<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/ronin-rekt">Ronin Network - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->624,000,000<!-- --> | <!-- -->03/23/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index-l">4<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/polynetwork-rekt">Poly Network - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->611,000,000<!-- --> | <!-- -->08/10/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index-l">5<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/bnb-bridge-rekt">BNB Bridge - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->586,000,000<!-- --> | <!-- -->10/06/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index-l">6<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/sbf-mask-off">SBF - MASK OFF<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->477,000,000<!-- --> | <!-- -->11/12/22</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index-l">7<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/wormhole-rekt">Wormhole - REKT<!-- --> <span class="leaderboard-audit">Neodyme</span></a></div><div class="leaderboard-row-details">$<!-- -->326,000,000<!-- --> | <!-- -->02/02/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index-l">8<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/dmm-rekt">DMM Bitcoin - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->304,000,000<!-- --> | <!-- -->05/30/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index-l">9<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/wazirx-rekt">WazirX - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->235,000,000<!-- --> | <!-- -->07/18/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">10<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/cetus-rekt">Cetus - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->223,000,000<!-- --> | <!-- -->5/22/2025</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">11<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/gala-games-rekt">Gala Games - Rekt<!-- --> <span class="leaderboard-audit">Anchain, Certik</span></a></div><div class="leaderboard-row-details">$<!-- -->216,000,000<!-- --> | <!-- -->05/20/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">12<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/mixin-rekt">Mixin Network - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->200,000,000<!-- --> | <!-- -->09/23/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">13<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/euler-rekt">Euler Finance - REKT<!-- --> <span class="leaderboard-audit">Sherlock</span></a></div><div class="leaderboard-row-details">$<!-- -->197,000,000<!-- --> | <!-- -->03/13/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">14<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/bitmart-rekt">BitMart - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->196,000,000<!-- --> | <!-- -->12/04/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">15<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/nomad-rekt">Nomad Bridge - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->190,000,000<!-- --> | <!-- -->08/01/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">16<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/beanstalk-rekt">Beanstalk - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->181,000,000<!-- --> | <!-- -->04/17/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">17<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/wintermute-rekt-2">Wintermute - REKT 2<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->162,300,000<!-- --> | <!-- -->09/20/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">18<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/compound-rekt">Compound - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->147,000,000<!-- --> | <!-- -->09/29/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">19<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/vulcan-forged-rekt">Vulcan Forged - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->140,000,000<!-- --> | <!-- -->12/13/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">20<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/cream-rekt-2">Cream Finance - REKT 2<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->130,000,000<!-- --> | <!-- -->10/27/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">21<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/balancer-rekt2">Balancer - Rekt II<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->128,000,000<!-- --> | <!-- -->11/3/2025</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">22<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/multichain-rekt2">Multichain - REKT 2<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->126,300,000<!-- --> | <!-- -->07/06/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">23<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/poloniex-rekt">Poloniex - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->126,000,000<!-- --> | <!-- -->11/10/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">24<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/bonq-rekt">BonqDAO - REKT<!-- --> <span class="leaderboard-audit">Out of scope</span></a></div><div class="leaderboard-row-details">$<!-- -->120,000,000<!-- --> | <!-- -->02/01/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">25<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/badger-rekt">Badger - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->120,000,000<!-- --> | <!-- -->12/02/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">26<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/mango-markets-rekt">Mango Markets - REKT<!-- --> <span class="leaderboard-audit">Out of Scope</span></a></div><div class="leaderboard-row-details">$<!-- -->115,000,000<!-- --> | <!-- -->10/11/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">27<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/atomic-wallet-rekt">Atomic Wallet - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->100,000,000<!-- --> | <!-- -->06/02/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">28<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/harmony-rekt">Harmony Bridge - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->100,000,000<!-- --> | <!-- -->06/23/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">29<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/heco-htx-rekt">HECO Bridge, HTX - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->99,100,000<!-- --> | <!-- -->11/22/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">30<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/mirror-rekt">Mirror Protocol - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->92,000,000<!-- --> | <!-- -->10/08/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">31<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/woo-rekt">Woofi - Rekt<!-- --> <span class="leaderboard-audit">Certik</span></a></div><div class="leaderboard-row-details">$<!-- -->85,000,000<!-- --> | <!-- -->03/05/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">32<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/orbit-bridge-rekt">Orbit Bridge - REKT<!-- --> <span class="leaderboard-audit">Out of scope</span></a></div><div class="leaderboard-row-details">$<!-- -->81,500,000<!-- --> | <!-- -->12/31/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">33<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/fei-rari-rekt">Fei Rari - REKT 2<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->80,000,000<!-- --> | <!-- -->05/01/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">34<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/qubit-rekt">Qubit Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->80,000,000<!-- --> | <!-- -->01/28/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">35<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/ascendex-rekt">Ascendex - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->77,700,000<!-- --> | <!-- -->12/12/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">36<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/phemex-rekt">Phemex - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->73,540,297<!-- --> | <!-- -->01/23/2025</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">37<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/curve-vyper-rekt">Curve, Vyper - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->69,300,000<!-- --> | <!-- -->07/30/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">38<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/munchables-rekt">Munchables - REKT<!-- --> <span class="leaderboard-audit">Entersof</span></a></div><div class="leaderboard-row-details">$<!-- -->62,500,000<!-- --> | <!-- -->03/26/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">39<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/alphapo-rekt">AlphaPo - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->60,000,000<!-- --> | <!-- -->07/22/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">40<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/easyfi-rekt">EasyFi - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->59,000,000<!-- --> | <!-- -->04/19/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">41<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/uranium-rekt">Uranium Finance - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->57,200,000<!-- --> | <!-- -->04/28/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">42<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/whale-hunters-payday">Whale Hunter's Payday<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->55,470,000<!-- --> | <!-- -->08/20/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">43<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/bzx-rekt">bZx - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->55,000,000<!-- --> | <!-- -->11/05/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">44<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/coinex-rekt">CoinEx - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->54,300,000<!-- --> | <!-- -->09/12/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">45<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/radiant-capital-rekt2">Radiant Capital - Rekt II<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->53,000,000<!-- --> | <!-- -->10/16/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">46<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/btcturk-rekt">BTCTurk - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->51,700,000<!-- --> | <!-- -->8/14/2025</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">47<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/infini-rekt">Infini - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->49,500,000<!-- --> | <!-- -->2/24/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">48<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/kyberswap-rekt">KyberSwap - REKT<!-- --> <span class="leaderboard-audit">ChainSecurity, Sherlock</span></a></div><div class="leaderboard-row-details">$<!-- -->48,000,000<!-- --> | <!-- -->11/22/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">49<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/cashio-rekt">Cashio - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->48,000,000<!-- --> | <!-- -->03/23/2022</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">50<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/pancakebunny-rekt">PancakeBunny - REKT<!-- --> <span class="leaderboard-audit">Unaudited</span></a></div><div class="leaderboard-row-details">$<!-- -->45,000,000<!-- --> | <!-- -->05/19/2021</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">51<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/epic-hack-homie">Kucoin - REKT<!-- --> <span class="leaderboard-audit">Internal audit</span></a></div><div class="leaderboard-row-details">$<!-- -->45,000,000<!-- --> | <!-- -->09/29/2020</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">52<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/bingx-rekt">BingX - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->44,700,000<!-- --> | <!-- -->09/19/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">53<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/hedgey-finance-rekt">Hedgey Finance - Rekt<!-- --> <span class="leaderboard-audit">Consensys Diligence</span></a></div><div class="leaderboard-row-details">$<!-- -->44,700,000<!-- --> | <!-- -->04/19/2024</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">54<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/coindcx-rekt">CoinDCX - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->44,300,000<!-- --> | <!-- -->7/18/2025</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">55<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/gmx-rekt">GMX - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->42,000,000<!-- --> | <!-- -->7/9/2025</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">56<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/stake-rekt">Stake - REKT<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->41,600,000<!-- --> | <!-- -->09/04/2023</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">57<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/swissborg-rekt">Swissborg - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->41,500,000<!-- --> | <!-- -->9/8/2025</div></div></div></li>,
 <li><div class="leaderboard-row"><span class="leaderboard-index">58<!-- -->.</span><div><div class="leaderboard-row-title"><a href="/uxlink-rekt">UXLink - Rekt<!-- --> <span class="leaderboard-audit">N/A</span></a></div><div class="leaderboard-row-details">$<!-- -->41,000,000<!-- --> | <!-- -->9/22/2025</div></div></div></li>,

In [25]:
table = soup.find_all('div', attrs = {'class':'leaderboard-row-details'})
table

[<div class="leaderboard-row-details">$<!-- -->14,847,374,246<!-- --> | <!-- -->12/20/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->1,436,173,027<!-- --> | <!-- -->2/21/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->624,000,000<!-- --> | <!-- -->03/23/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->611,000,000<!-- --> | <!-- -->08/10/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->586,000,000<!-- --> | <!-- -->10/06/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->477,000,000<!-- --> | <!-- -->11/12/22</div>,
 <div class="leaderboard-row-details">$<!-- -->326,000,000<!-- --> | <!-- -->02/02/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->304,000,000<!-- --> | <!-- -->05/30/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->235,000,000<!-- --> | <!-- -->07/18/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->223,000,000<!-- --> | <!-- -->5/22/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->216,000,000<!-- --> | <!-- -->05/20/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->200,000,000<!-- --> | <!-- -->09/23/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->197,000,000<!-- --> | <!-- -->03/13/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->196,000,000<!-- --> | <!-- -->12/04/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->190,000,000<!-- --> | <!-- -->08/01/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->181,000,000<!-- --> | <!-- -->04/17/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->162,300,000<!-- --> | <!-- -->09/20/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->147,000,000<!-- --> | <!-- -->09/29/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->140,000,000<!-- --> | <!-- -->12/13/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->130,000,000<!-- --> | <!-- -->10/27/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->128,000,000<!-- --> | <!-- -->11/3/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->126,300,000<!-- --> | <!-- -->07/06/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->126,000,000<!-- --> | <!-- -->11/10/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->120,000,000<!-- --> | <!-- -->02/01/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->120,000,000<!-- --> | <!-- -->12/02/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->115,000,000<!-- --> | <!-- -->10/11/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->100,000,000<!-- --> | <!-- -->06/02/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->100,000,000<!-- --> | <!-- -->06/23/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->99,100,000<!-- --> | <!-- -->11/22/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->92,000,000<!-- --> | <!-- -->10/08/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->85,000,000<!-- --> | <!-- -->03/05/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->81,500,000<!-- --> | <!-- -->12/31/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->80,000,000<!-- --> | <!-- -->05/01/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->80,000,000<!-- --> | <!-- -->01/28/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->77,700,000<!-- --> | <!-- -->12/12/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->73,540,297<!-- --> | <!-- -->01/23/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->69,300,000<!-- --> | <!-- -->07/30/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->62,500,000<!-- --> | <!-- -->03/26/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->60,000,000<!-- --> | <!-- -->07/22/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->59,000,000<!-- --> | <!-- -->04/19/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->57,200,000<!-- --> | <!-- -->04/28/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->55,470,000<!-- --> | <!-- -->08/20/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->55,000,000<!-- --> | <!-- -->11/05/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->54,300,000<!-- --> | <!-- -->09/12/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->53,000,000<!-- --> | <!-- -->10/16/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->51,700,000<!-- --> | <!-- -->8/14/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->49,500,000<!-- --> | <!-- -->2/24/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->48,000,000<!-- --> | <!-- -->11/22/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->48,000,000<!-- --> | <!-- -->03/23/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->45,000,000<!-- --> | <!-- -->05/19/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->45,000,000<!-- --> | <!-- -->09/29/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->44,700,000<!-- --> | <!-- -->09/19/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->44,700,000<!-- --> | <!-- -->04/19/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->44,300,000<!-- --> | <!-- -->7/18/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->42,000,000<!-- --> | <!-- -->7/9/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->41,600,000<!-- --> | <!-- -->09/04/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->41,500,000<!-- --> | <!-- -->9/8/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->41,000,000<!-- --> | <!-- -->9/22/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->37,500,000<!-- --> | <!-- -->02/13/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->37,000,000<!-- --> | <!-- -->12/14/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->34,000,000<!-- --> | <!-- -->09/21/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->33,700,000<!-- --> | <!-- -->01/18/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->33,000,000<!-- --> | <!-- -->04/20/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->32,000,000<!-- --> | <!-- -->03/04/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->31,400,000<!-- --> | <!-- -->11/30/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->30,500,000<!-- --> | <!-- -->05/02/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->30,000,000<!-- --> | <!-- -->12/18/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->28,000,000<!-- --> | <!-- -->11/01/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->27,600,000<!-- --> | <!-- -->06/05/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->27,300,000<!-- --> | <!-- -->1/31/2026</div>,
 <div class="leaderboard-row-details">$<!-- -->27,000,000<!-- --> | <!-- -->7/15/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->27,000,000<!-- --> | <!-- -->09/03/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->27,000,000<!-- --> | <!-- -->06/23/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->27,000,000<!-- --> | <!-- -->03/05/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->26,200,000<!-- --> | <!-- -->1/8/2026</div>,
 <div class="leaderboard-row-details">$<!-- -->26,000,000<!-- --> | <!-- -->11/18/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->25,220,000<!-- --> | <!-- -->09/10/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->25,000,000<!-- --> | <!-- -->10/26/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->24,000,000<!-- --> | <!-- -->9/24/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->24,000,000<!-- --> | <!-- -->12/02/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->24,000,000<!-- --> | <!-- -->05/12/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->23,000,000<!-- --> | <!-- -->07/31/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->22,200,000<!-- --> | <!-- -->04/12/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->21,800,000<!-- --> | <!-- -->05/13/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->21,200,000<!-- --> | <!-- -->10/02/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->21,000,000<!-- --> | <!-- -->03/08/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->20,000,000<!-- --> | <!-- -->05/15/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->20,000,000<!-- --> | <!-- -->08/03/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->19,700,000<!-- --> | <!-- -->11/22/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->19,400,000<!-- --> | <!-- -->06/10/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->18,800,000<!-- --> | <!-- -->08/30/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->18,100,000<!-- --> | <!-- -->11/25/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->18,000,000<!-- --> | <!-- -->05/17/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->16,180,000<!-- --> | <!-- -->6/6/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->16,000,000<!-- --> | <!-- -->03/23/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->16,000,000<!-- --> | <!-- -->10/14/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->15,800,000<!-- --> | <!-- -->10/27/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->15,600,000<!-- --> | <!-- -->04/02/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->15,000,000<!-- --> | <!-- -->09/28/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->14,000,000<!-- --> | <!-- -->7/24/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->14,000,000<!-- --> | <!-- -->02/27/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->13,700,000<!-- --> | <!-- -->10/31/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->13,400,000<!-- --> | <!-- -->04/28/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->12,913,691<!-- --> | <!-- -->3/25/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->12,000,000<!-- --> | <!-- -->5/28/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->12,000,000<!-- --> | <!-- -->08/07/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->12,000,000<!-- --> | <!-- -->12/02/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->11,700,000<!-- --> | <!-- -->03/15/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->11,600,000<!-- --> | <!-- -->03/28/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->11,400,000<!-- --> | <!-- -->04/13/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->11,000,000<!-- --> | <!-- -->12/02/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->11,000,000<!-- --> | <!-- -->05/07/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->11,000,000<!-- --> | <!-- -->02/05/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->10,970,000<!-- --> | <!-- -->2/22/2026</div>,
 <div class="leaderboard-row-details">$<!-- -->10,000,000<!-- --> | <!-- -->02/10/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->10,000,000<!-- --> | <!-- -->01/04/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->10,000,000<!-- --> | <!-- -->05/08/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->10,000,000<!-- --> | <!-- -->05/05/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->9,800,000<!-- --> | <!-- -->6/25/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->9,730,000<!-- --> | <!-- -->07/16/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->9,570,000<!-- --> | <!-- -->02/11/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->9,400,000<!-- --> | <!-- -->12/29/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->9,000,000<!-- --> | <!-- -->11/30/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->9,000,000<!-- --> | <!-- -->11/18/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->8,950,000<!-- --> | <!-- -->08/10/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->8,900,000<!-- --> | <!-- -->03/28/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->8,800,000<!-- --> | <!-- -->07/02/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->8,700,000<!-- --> | <!-- -->11/16/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->8,700,000<!-- --> | <!-- -->02/08/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->8,500,000<!-- --> | <!-- -->02/17/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->8,400,000<!-- --> | <!-- -->9/1/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->8,400,000<!-- --> | <!-- -->3/21/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->8,400,000<!-- --> | <!-- -->10/19/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->8,200,000<!-- --> | <!-- -->12/21/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->8,000,000<!-- --> | <!-- -->07/02/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->8,000,000<!-- --> | <!-- -->07/22/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->8,000,000<!-- --> | <!-- -->11/17/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->7,940,000<!-- --> | <!-- -->01/08/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->7,900,000<!-- --> | <!-- -->09/24/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->7,900,000<!-- --> | <!-- -->07/10/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->7,800,000<!-- --> | <!-- -->12/18/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->7,700,000<!-- --> | <!-- -->02/06/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->7,500,000<!-- --> | <!-- -->07/19/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->7,500,000<!-- --> | <!-- -->10/17/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->7,500,000<!-- --> | <!-- -->05/28/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->7,491,500<!-- --> | <!-- -->4/14/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->7,400,000<!-- --> | <!-- -->04/15/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->7,200,000<!-- --> | <!-- -->08/18/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->7,200,000<!-- --> | <!-- -->05/28/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->7,000,000<!-- --> | <!-- -->1/21/2026</div>,
 <div class="leaderboard-row-details">$<!-- -->7,000,000<!-- --> | <!-- -->8/12/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->7,000,000<!-- --> | <!-- -->11/14/2020</div>,
 <div class="leaderboard-row-details">$<!-- -->6,943,774<!-- --> | <!-- -->02/4/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->6,800,000<!-- --> | <!-- -->06/02/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->6,500,000<!-- --> | <!-- -->01/30/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->6,500,000<!-- --> | <!-- -->05/05/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->6,500,000<!-- --> | <!-- -->12/10/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->6,500,000<!-- --> | <!-- -->06/16/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->6,400,000<!-- --> | <!-- -->07/30/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->6,400,000<!-- --> | <!-- -->02/28/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->6,300,000<!-- --> | <!-- -->05/29/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->6,000,000<!-- --> | <!-- -->07/23/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->5,980,000<!-- --> | <!-- -->09/15/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->5,900,000<!-- --> | <!-- -->07/15/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->5,800,000<!-- --> | <!-- -->4/26/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->5,800,000<!-- --> | <!-- -->06/16/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->5,700,000<!-- --> | <!-- -->03/14/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->5,300,000<!-- --> | <!-- -->08/02/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->5,000,000<!-- --> | <!-- -->8/26/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->5,000,000<!-- --> | <!-- -->3/5/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->5,000,000<!-- --> | <!-- -->07/15/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->4,900,000<!-- --> | <!-- -->09/20/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->4,850,000<!-- --> | <!-- -->11/11/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->4,800,000<!-- --> | <!-- -->03/21/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->4,500,000<!-- --> | <!-- -->8/4/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->4,500,000<!-- --> | <!-- -->01/04/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->4,500,000<!-- --> | <!-- -->01/02/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->4,500,000<!-- --> | <!-- -->08/29/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->4,500,000<!-- --> | <!-- -->06/22/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->4,400,000<!-- --> | <!-- -->2/21/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->4,400,000<!-- --> | <!-- -->10/18/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->4,400,000<!-- --> | <!-- -->07/01/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->4,400,000<!-- --> | <!-- -->12/16/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->4,400,000<!-- --> | <!-- -->07/11/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->4,300,000<!-- --> | <!-- -->05/14/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->4,200,000<!-- --> | <!-- -->07/21/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->4,130,000<!-- --> | <!-- -->1/20/2026</div>,
 <div class="leaderboard-row-details">$<!-- -->4,000,000<!-- --> | <!-- -->03/26/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->4,000,000<!-- --> | <!-- -->03/31/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->4,000,000<!-- --> | <!-- -->09/04/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->3,800,000<!-- --> | <!-- -->09/25/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->3,760,000<!-- --> | <!-- -->6/1/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->3,650,000<!-- --> | <!-- -->02/09/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->3,600,000<!-- --> | <!-- -->7/15/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->3,500,000<!-- --> | <!-- -->07/28/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->3,400,000<!-- --> | <!-- -->07/25/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->3,300,000<!-- --> | <!-- -->01/16/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->3,300,000<!-- --> | <!-- -->11/10/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->3,300,000<!-- --> | <!-- -->04/09/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->3,200,000<!-- --> | <!-- -->11/02/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->3,100,000<!-- --> | <!-- -->11/20/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->3,100,000<!-- --> | <!-- -->09/17/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->3,000,000<!-- --> | <!-- -->9/24/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->3,000,000<!-- --> | <!-- -->9/12/2025</div>,
 <div class="leaderboard-row-details">$<!-- -->3,000,000<!-- --> | <!-- -->09/19/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->3,000,000<!-- --> | <!-- -->06/09/2024</div>,
 <div class="leaderboard-row-details">$<!-- -->3,000,000<!-- --> | <!-- -->05/18/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->3,000,000<!-- --> | <!-- -->02/02/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->3,000,000<!-- --> | <!-- -->05/08/2022</div>,
 <div class="leaderboard-row-details">$<!-- -->3,000,000<!-- --> | <!-- -->03/15/2021</div>,
 <div class="leaderboard-row-details">$<!-- -->2,900,000<!-- --> | <!-- -->10/07/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->2,790,000<!-- --> | <!-- -->10/09/2023</div>,
 <div class="leaderboard-row-details">$<!-- -->2,700,000<!-- --> | <!-- -->12/12/2025</div>,

In [26]:
print(len(table))

284

In [27]:
main = []
# Create a master list of conglomerated amounts and dates
for item in soup.select('div.leaderboard-row-details'):
    main.append(item.text)

In [28]:
main[0:5]

['$14,847,374,246 | 12/20/2020',
 '$1,436,173,027 | 2/21/2025',
 '$624,000,000 | 03/23/2022',
 '$611,000,000 | 08/10/2021',
 '$586,000,000 | 10/06/2022']

In [29]:
dates = []
for item in main:
    dates = [elem.replace('000,000 | ', '') for elem in dates]
    s1 = slice(8,27,1)
    dates.append(item[s1])

In [30]:
dates[:5]

['374,246 | 12/20/202',
 '73,027 | 2/21/2025',
 ',000 | 03/23/2022',
 ',000 | 08/10/2021',
 ',000 | 10/06/2022']

In [31]:
clean_dates = []
for item in dates:
    regex = " (\\d{2}/\\d{2}/\\d{4})";
    i = item.lstrip(',000,000 | ')
    
    clean_dates.append(i)

In [32]:
# A list of all of the cleaned dates
clean_dates[0:5]

['374,246 | 12/20/202',
 '73,027 | 2/21/2025',
 '3/23/2022',
 '8/10/2021',
 '10/06/2022']

In [33]:
len(clean_dates)

284

In [34]:
main[0:5]

['$14,847,374,246 | 12/20/2020',
 '$1,436,173,027 | 2/21/2025',
 '$624,000,000 | 03/23/2022',
 '$611,000,000 | 08/10/2021',
 '$586,000,000 | 10/06/2022']

In [35]:
amt = []
for item in main:
    amt = [elem.replace(' | ', '') for elem in amt]
    s2 = slice(0,13,1)
    amt.append(item[s2])

In [36]:
amt[0:5]

['$14,847,374,2',
 '$1,436,173,02',
 '$624,000,000 ',
 '$611,000,000 ',
 '$586,000,000 ']

In [37]:
clean_amt = []
for x in amt:
    i = x.rstrip('| ')           
    clean_amt.append(i)

In [38]:
# The last 6 elements will have to be manually cleaned which is not a grueling burden
clean_amt[0:5]

['$14,847,374,2',
 '$1,436,173,02',
 '$624,000,000',
 '$611,000,000',
 '$586,000,000']

In [39]:
print(len(clean_amt))

284

In [40]:
# Testing if the length of each list are equal so the DataFrame
# is built with the proper dimensions
if (len(clean_amt) == len(exp_list)) and (len(exp_list) == len(clean_dates)):
    print(True)
else:
    print(False)

True

In [41]:
exp_list[0:5]

[',bybit', ',ronin', ',polynetwork', ',bnbbridge', ',sbfmaskoff']

In [42]:
df = pd.DataFrame(exp_list, columns= ["protocol_name"])
df.head()

  protocol_name
0        ,bybit
1        ,ronin
2  ,polynetwork
3    ,bnbbridge
4   ,sbfmaskoff

In [43]:
df1 = pd.DataFrame(clean_dates, columns= ["date_of_attack"])
df1.head()

        date_of_attack
0  374,246 | 12/20/202
1   73,027 | 2/21/2025
2            3/23/2022
3            8/10/2021
4           10/06/2022

In [44]:
df2 = pd.DataFrame(clean_amt, columns= ["amount_lost"])
df2.head()

     amount_lost
0  $14,847,374,2
1  $1,436,173,02
2   $624,000,000
3   $611,000,000
4   $586,000,000

In [45]:
df=df.join(df1)
df.head()

  protocol_name       date_of_attack
0        ,bybit  374,246 | 12/20/202
1        ,ronin   73,027 | 2/21/2025
2  ,polynetwork            3/23/2022
3    ,bnbbridge            8/10/2021
4   ,sbfmaskoff           10/06/2022

In [46]:
# Final DataFrame with all columns appended
# Special thanks to BeautifulSoup
df=df.join(df2)
df.head()

  protocol_name       date_of_attack    amount_lost
0        ,bybit  374,246 | 12/20/202  $14,847,374,2
1        ,ronin   73,027 | 2/21/2025  $1,436,173,02
2  ,polynetwork            3/23/2022   $624,000,000
3    ,bnbbridge            8/10/2021   $611,000,000
4   ,sbfmaskoff           10/06/2022   $586,000,000

In [47]:
# Converting dataframe data to Excel
# The data stored accounts for the rekt 2020-2021 leaderboard
df.to_excel('REAL_rektnews_ws.xlsx', index=False)